### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#19]
@kimdhamilton 

I'd like to directly invoke (i.e, not through REST) the operations in sign-and-verify (because I'm trying to build that pseudo-wallet I mentioned - i.e, a web page that pretends to be a wallet for testing purposes).  

Specifically, I want the methods that are returned by createIssuer(config: Config) in issuer.ts:

sign
signPresentation
createAndSignPresentation
verify
verifyPresentation
requestDemoCredential

I think the new NPM package (https://www.npmjs.com/package/@digitalcredentials/sign-and-verify) is probably intended to do this, and maybe just needs a few more changes (or is the NPM package meant for something else)?  

I'm thinking that the issuer.ts (and related files) could be moved to its own repository, leaving the RESTful part (the fastify stuff in index.ts) in sign-and-verify. (or vice versa, move the fastify stuff into a new repository)  This new 'dcc-issuer' (or whatever it should be called) repo becomes the NPM module, and has an index.js (that is set as 'main' in package.json) that exports one method: createIssuer(config: Config)

Then the createIssuer method could be directly used in another project (say a Wallet - either app or web based) by installing the NPM module (with npm/yarn), importing the method, and using it (passing in a config):

import createIssuer from "issuer";
const { sign, verify, createAndSignPresentation, signPresentation, verifyPresentation, requestDemoCredential } = createIssuer(getConfig());
let didAuthResponse = createAndSignPresentation(null, presentationId, holder, options)
// then send off didAuthResponse to the issuer endpoint.

The fastify code would also now install this new npm module and use it just like it had used it before, only now it is coming from the npm repository.

If this all seems right I am happy to create the new repository tomorrow (I'd leave the sign-and-verify as is so as not to break anything - basically I'd just create a new repo that can publish an npm package that exposes the createIssuer method)

**Comment by dmitrizagidulin** [comment]
@jchartrand 
+1, seems like a decent idea (to separate out the fastify http API app and the core library). My vote is to name the other one - `sign-and-verify-core`.

**Comment by kimdhamilton** [comment]
Thanks @jchartrand -- that was definitely originally the intent, but I probably lost track of that. 

The only reason I'm reluctant to separate out repos is that it can be a pain to keep everything up to date when APIs are new, so I wanted to see if other options would work:

1. @stuartf did something similar for credgen, exposing a [lib](https://github.com/digitalcredentials/credgen/blob/master/src/lib.ts) while also exposing the CLI.
2. Orie uses lerna for multi-module management. I haven't figured that out yet, but that at least lets you keep everything in the same repo.

**Comment by jchartrand** [comment]
@kimdhamilton @dmitrizagidulin @stuartf 

I totally understand not wanting a proliferation of npm packages.  I've out-clevered myself on that before.

In this case, though, the part that just doesn't seem to belong in an npm package is the fastify stuff.  I'm not sure how one would even use that part after installing the sign-and-verify npm package?

One option for making simultaneous changes during development to the web app (fastify) and the sign-and-verify-core -- without having to constantly re-publish to npm, and `npm install` for every change -- is to use `npm link` to pull in a local dev copy of the sign-and-verify-core, like described here:  https://www.deadcoderising.com/how-to-smoothly-develop-node-modules-locally-using-npm-link/

I hadn't heard of Lerna - it looks very useful, and I'm happy to help incorporate it into sign-and-verify (or elsewhere), although for the moment I think the single sign-and-verify-core might be the only npm package we have (again, I'm just not sure the fastify stuff belongs in an npm package, but happy to be proven wrong, and learn something new).

**Comment by kimdhamilton** [comment]
I see what you're saying with fastify. It would be nice if we could use some multi-module/monorepo solution, at least in the early days, to minimize repo proliferation. I'd definitely be interested in that, if you could help. If it starts to look too complicated, let me know and we can do multiple repos instead

**Comment by kimdhamilton** [comment]
Tagging @blarghmatey -- xPro's service deployment depends on the structure of this repo, so I want to make sure we don't break him

**Comment by blarghmatey** [comment]
My deployment only depends on the output of the Dockerfile build, so as long as we can keep that working then I have no horse in this race.

**Comment by jchartrand** [comment]
I won't change this repo.  I'll just make a new one (called sign-and-verify-base as suggested by @dmitrizagidulin) that includes everything except fastify, and publish that new repo to npm.  Once I'm done maybe then we can look at importing the new npm package into fastify?

**Comment by kimdhamilton** [comment]
Strong no. I'm not sure that approach is sustainable because we'd have to copy code changes to both repos. Can we at least look into multimodule solutions?

**Comment by kimdhamilton** [comment]
See for example [this](https://github.com/transmute-industries/material-did/tree/master/packages), which keeps the code in the same repo, but allows independent publishing of modules. I have to put my foot down to code copying in multiple repos as the most abhorrent possible option :)

**Comment by jchartrand** [comment]
I didn't at all mean that we'd keep two copies of the same code (that would indeed be silly, as you point out).  I just meant that I could get everything working with this extracted core module (in a new repo), and only then consider how it could be incorporated into fastify (which would likely just be as a standard import).

**Comment by jchartrand** [comment]
My ill-expressed point was just that I won't go breaking anything in this repo while I'm extracting the npm core module.

**Comment by kimdhamilton** [comment]
thanks for clarifying :) After a long morning of CCG mailing list shenanigans my brain is fried. :)

When you say import "into fastify" to you mean import into this repo, which uses fastify? i.e. structurally:

This repo (sign-and-verify) would do the following, in its end state?
- exposes service endpoint
- calls operations on sign-and-verify-core

Does it have to be a new repo as opposed to multi-module, which could be easier to manage (unless there's some github automation that would help update this repo when core changes? maybe there are other options? ).

**Comment by jchartrand** [comment]
> When you say import "into fastify" to you mean import into this repo, which uses fastify? i.e. structurally:
> 
> This repo (sign-and-verify) would do the following, in its end state?
> 
> * exposes service endpoint
> * calls operations on sign-and-verify-core

Yes, exactly.

> 
> Does it have to be a new repo as opposed to multi-module, which could be easier to manage (unless there's some github automation that would help update this repo when core changes? maybe there are other options? ).

I thought it would be confusing to have the api server stuff (fastify) or Docker for that matter - neither of which are 'packagable' in any useful 'importable' sense (I don't think?) - in the same repo as code that is meant to be published as an importable NPM package (or packages) - even if using lerna - but I see that at least one person describes doing just that:

https://github.com/erzhtor/javascript-monorepo-with-lerna

so happy to give it a try if that's best.

**Comment by kimdhamilton** [comment]
Ok, I buy that. The server part is package-able in the docker sense, but you're right, it's not an npm package.

Figuring that out and maintaining it may actually be more awkward than just splitting the repos (I haven't looked into it), so feel free to create a new repo for this. You should have permission to do so (let me know if not)

**Comment by jchartrand** [comment]
@blarghmatey @kimdhamilton @dmitrizagidulin @rhysyngsun @stuartf 

Very sorry all, I accidentally committed a change that was meant for a new copy of the repo (I hadn't changed the remote origin).  I've reverted the commit.

**Comment by kimdhamilton** [comment]
@jchartrand fixed this by adding sign-and-verify-core and updating this
