### ISSUE TITLE
Unable to sign credentials due to schema conflicts

### ISSUE THREAD

**Issue by rhysyngsun** [digitalcredentials/sign-and-verify#22]
It seems like there's been some upstream schema changes that are occasionally causing our requests to break, for example a recent error:

```
Error: The property "educationalCredentialAwarded" in the input was not defined in the context.
```

This is based on our template we were planning on using for https://github.com/mitodl/mitxpro/issues/1969

**Comment by kimdhamilton** [comment]
@rhysyngsun -- thanks for finding this, and sorry it took a while to fix/test. I believe everything is addressed now:

1. Key changes are described in https://github.com/digitalcredentials/sign-and-verify-core/pull/1
2. Updated this service and other upstream callers
3. Updated https://github.com/mitodl/mitxpro/issues/1969; note that both samples changed (as well as the diagram and description)

Let me know if you run into any issues or have questions

**Comment by rhysyngsun** [comment]
Working for xPro now
