### ISSUE TITLE
types file duplicated in sign-and-verify-core

### ISSUE THREAD

**Issue by stuartf** [digitalcredentials/sign-and-verify#24]
It looks like https://github.com/digitalcredentials/sign-and-verify/blob/master/src/types.ts and https://github.com/digitalcredentials/sign-and-verify-core/blob/master/src/types.ts are the same file and need to match for type compatibility. I'd think we should export those types from sign-and-verify-core and import them here (and anywhere else we need to build a `DIDDocument`).

**Comment by kimdhamilton** [comment]
Fixed
