### ISSUE TITLE
Create a test web page in sign-and-verify with deeplink and CHAPI 'get'

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#59]
Create a web page in sign-and-verify (as a route that returns HTML) that provides:

-  a deep link into the LCW 
- a button that invokes a CHAPI 'get' containing a VPR

The deeplink will be preconfigured to call the forthcoming '/exchange/{exchangeId} endpoint, where the {exchangeId) will be called 'test' and the 'challenge' will also be called 'test'.  So, the deeplink would have params like so:

auth_type: 'bearer'
vc_request_url: '/exchange/test
challenge: 'test'

The deeplink will open the LCW, and the LCW will sign a DIDAuth containing the challenge and the holder DID, then call the vc_request_url (which is just another route in the same sign-and-verify as the web page).

The sign-and-verify exchange endpoint would need to recognize the 'test' exchangeId and issue a preset test credential.

The CHAPI invocation will do more or less the same thing but passing in a VPR on a CHAPI 'get' request.  The VPR will specific the endpoint and the challenge, and would likely look like this:

https://w3c-ccg.github.io/vp-request-spec/#example-example-interact-request

**Comment by kayaelle** [comment]
Closing but we will create a demo site soon using new sign-and-verify refactoring
