### ISSUE TITLE
verify incoming challenge

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#66]
The sign-and-verify /exchanges/{exchangeId} (and it's alias /request/credential) endpoint receives an incoming DIDAuth that contains a challenge that, as things stand, is created by whoever created the deeplink/CHAPI request.  But the endpoint doesn't have access to the original challenge to verify that the challenge in the incoming DID Auth VP (which was passed on the deeplink or CHAPI request) matches the original.

Whoever generates the challenge needs a way to pass it in to sign-and-verify (e.g., some endpoint to which it can post the challenge, which sign-and-verify then stores and uses later to compare to the incoming DIDAuth), or alternatively needs to ask sign-and-verify to generate and return the challenge (and store it for later comparison).

Alternatively, we could pass off all of the challenge management to sign-and-verify, so: generation of the challenge, storage of the challenge, and comparison of the challenge, along with creation of the deeplink, etc. as described in #67

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify
