### ISSUE TITLE
New endpoint /credentials/distribute to manage entire wallet exchange for issuer

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#67]
As things stand with sign-and-verify, we leave it up to the issuer (i.e, a school that wants to use sign-and-verify) to manage:

at setup time:

- confirming their OIDC system works with LCW, including adding OIDC endpoints, etc. to DCC config file
- setup of Mongo DB
- installation and configure of sign-and-verify including adding DB config details

and at issuance time:

- adding credential data to Mongo (via CSV upload, or however issuer wants to add it)
- managing how a holder requests a specific credential (e.g., from course page or from a degree download page)
- generating a challenge (although we don't currently have any way to pass that challenge to sign-and-verify to later use when validating the DID-auth - see #66)
- construct the deep link (or CHAPI request)
- making the deeplink or CHAPI request available somehow (email, web page) - including the CHAPI poly fills

I think we could handle a few of the tricky things here for the issuer by providing a new endpoint in sign-and-verify (called something like /credentials/distribute).  

The issuer will redirect to this new endpoint (after the holder has clicked some button on some campus page asking for a credential), passing along the data for a specific credential (e.g., degree details for James Chartrand).  The endpoint will take care of the rest including: the challenge generation/management, deeplink/chapi request, request endpoint that receives DID Auth, validation of challenge, VC construction, signing, revocation position allocation, logging, etc.  

The endpoint would likely first show a web page that explained to the holder that they are about to download a credential (and maybe show them some of the passed in details), and that they need to install a wallet, be looking at the current page in a web browser on their phone, etc.   The page would also provide them with various different links (options) including:

- deeplink if using LCW (or any other wallet that we support that requires a deep link)
- CHAPI 'get' request (and the CHAPI polyfill)
- possibly an option to get a PDF copy with a QR
- maybe just a QR they could scan right then and there from a wallet like LCW
- any other options we want to provide (direct storage via WebVerifierPlus?)

The holder would choose an option, e.g, clicking the LCW deeplink, which would open the wallet and pass in the deeplink, which the wallet parses, generates a DID Auth, and submits back to the request end point.  The endpoint then receives DID Auth, checks it, including the challenge, constructs the credential (using data it stored with the challenge), signs it, allocates revocation position, logs the credential, and returns it.

This would lessen the burden on the issuer.  The issuer would no longer have to:

- generate a challenge or manage its expiration
- construct a deeplink or chapi request (or have to include the chapi polyfill, including maintaining updates to that polyfill)
- no longer have to make their OIDC system (or SAML) work with the wallet

They would still have to have an authenticated web page from which the student can choose the credential they want, and they'd have to retrieve the credential data from somewhere, either at the moment of request, or by adding it to the MongoDB at some point (although I suspect many issuers will not want to have to maintain yet another DB and would prefer to just use their existing campus or course DB). Both these things though - retrieving credential data and making an authenticated web page - are almost certainly things the university is already very comfortable doing.

Note that this endpoint could also make it much easier to provide this as a hosted service.  No longer would the issuer have to upload data to a hosted Mongo instance, or worry about how authentication works, or how exchange with the wallet works (deeplink, etc.)  The issuer just posts the credential data to the server and it handles everything else.  It would become a lot more like the /credentials/issue endpoint which provides something like a simple hosted signing service, without requiring any back channel calls to sign-and-verify.

The data that would get posted to the new endpoint could be something like:

```
{
	type: 'degree'
	issuerName: 'Queen's University",
	holder: 'James Chartrand',
	degreeType: 'Bachelor of Science",
	program: "Computer Science",
	yearIssued: '1994'
	callback: 'http://locahost:3333/credentialIssuedCallback
}
```

The callback would be invoked after the credential has been issued, giving the issuer a way to record the issuance in their local systems if they wanted to.

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify
