### ISSUE TITLE
multi-tenant issuance

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#68]
Probably want to allow issuers to use a single instance of sign-and-verify (and in particular with a DCC hosted copy) to issue more than one credential type, possibly with each signed with a different DID.

For the /exchanges/{exchangeId} endpoint (formally known in sign-and-verify as /request/credentials) we could add columns (properties) to the mongo record that allow specifying a different credential template, possibly different issuer data (although that could be part of the template), and a different signing DID to use.

For the /credentials/issue endpoint we could either use a different HMAC per credential type, or use a different path in the credential endpoint, like:

https://someServer.org/{tenantId}/credentials/issue

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify
