### ISSUE TITLE
Remove HMAC verification on endpoints

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#72]
Relic of some prior implementation with no known current use, and we should use OIDC instead anyhow.

**Comment by jchartrand** [comment]
The HMAC verification seems to be interfering with the chapi.io playground tests on the deployed JFF version of sign-and-verify (although doesn't with a locally hosted copy of sign-and-verify).  In any case, the HMAC stuff isn't used anymore so we are removing it.  High priority because we need to get the JFF endpoint working and registered in playground.chapi.io

**Comment by dmitrizagidulin** [comment]
+1 to close.
