### ISSUE TITLE
look at converging with cred-admin and lit-issuer

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#73]
Both sign-and-verify and cred-admin use sign-and-verify-core and both now use a local database for credential storage.  Could well be an opportunity to merge the two.

https://github.com/digitalcredentials/cred-admin

https://github.com/digitalcredentials/lti-issuer

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify. But we should discuss in terms of cred-admin.
