### ISSUE TITLE
Add contexts for chapi playground credentials

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#75]
Need to add these contexts:

https://playground.chapi.io/examples/alumni/alumni-v1.json
https://w3id.org/citizenship/v1
https://playground.chapi.io/examples/movieTicket/ticket-v1.json

to:

https://github.com/digitalcredentials/sign-and-verify-core/blob/9505e8ce70b99abf5a1f3f11db94656de2862e6f/src/common.ts#L15

**Comment by kayaelle** [comment]
Suggest we close since we are refactoring sign-and-verify
