### ISSUE TITLE
Add server-to-server OAuth

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/sign-and-verify#77]
Look at securing endpoints with something like:  

https://github.com/digitalbazaar/authorize-access-token-middleware/blob/main/lib/authorizeAccessToken.js#L153 

for a simple static token check, and possibly:

https://github.com/digitalbazaar/oauth2-client-registration-handler
https://github.com/digitalbazaar/oauth2-token-endpoint-handler

for a more robust OAuth that expires access tokens.

Could also layer in IP filtering.

**Comment by kayaelle** [comment]
Suggest we close this since we are working on the refactoring of sign-and-verify.

**Comment by dmitrizagidulin** [comment]
Agree it's ok to close it (though we should probably transfer this particular issue to, say, the `signing-service` or similar repo).
