### ISSUE TITLE
Before issuing, perform json schema verification

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/sign-and-verify#8]
We should check that required fields exist, the VC is well-formed, etc.

Notes:
- Does a VC json schema already exist? Let's create one if not.
- Also perform additional schema validation if a specific VC extension schema exists

**Comment by jchartrand** [comment]
I've added a schema check to /credentials/issue that uses Fastify to check the submitted VC.  Not entirely sure the schema I've created is correct, though (I based it off the schema defined at https://w3c-ccg.github.io/vc-api/#issue-credential), or if it should live somewhere else.
